= asciidocr

A(n in-progress, unstable, incomplete) Rust library for processing Asciidoc files.

== Usage (Command-Line)

Library usage is still TBD. To use the in-progress CLI tool, clone the repo,
install the crate with `cargo install --path .`. Here's the usage:

----
$ asciidocr -- help
A Rust CLI and library for processing Asciidoc files.

Usage: asciidocr [OPTIONS] <FILE>

Arguments:
  <FILE>  Asciidoc file for processing. To read from standard input (stdin), use "-"

Options:
  -o, --output-file <OUTPUT>  Optionally, provide a filename for the output. Defaults to FILE.<format>. To send to standard out (stdout), use "-"
  -a, --tck-adapter           Flag for returning the asciidoc Abstract Syntax Graph (asg); used for validation with the official Asciidoc Technology Compatibility Kit (TCK)
  -h, --help                  Print help
----

== Current State Notes (As of the Last README Commit)

_We have output_! You can now convert, for example, this entire README using the
`asciidocr` command to a fairly bare-bones HTML more or less along the lines of
what O'Reilly's https://oreillymedia.github.io/HTMLBook/[HTMLBook] expects.

There are still plenty of edge-cases and, in fact, tokens to be
parsed/implemented, but we've got headings, paragraphs, lists, and links, and
you can go pretty far with those. And frankly I needed a break from the parsing,
so I figured I'd change lanes for a little bit and work on the HTML output.

== Project Goals 

A non-exhaustive list:

* Coverage of the majority, if not all, of the language features, probably
  initially targeting a set similar to that of the `libasciidoc` project.
* Clean, simple HTML output as a default
* Build-in styles on said html output, but, like, a very small set.
* Native "document" (`docx` or `odt`, probably `docx`) output; given that part
  of the goal of this project is to make it easier for non-technical writers to
  use asciidoc, and given that most publishers, journals, business people, etc.,
  still want MS Word files, these should be easy to produce. (Also
  differentiates this project's capabilities from that of `asciidoctor`)
* PyO3 hooks for use inside Python contexts... eventually

