= asciidocr

A(n in-progress, incomplete, but more or less functional) Rust library for processing Asciidoc files.

== Usage (Command-Line)

Library usage is still TBD. To use the in-progress CLI tool, clone the repo,
install the crate with `cargo install --path .`. Here's the usage:

[source, bash]
----
$ asciidocr --help
A Rust CLI and library for processing Asciidoc files.

Usage: asciidocr [OPTIONS] <FILE>

Arguments:
  <FILE>
          Asciidoc file for processing. To read from standard input (stdin), use "-"

Options:
  -o, --out-file <OUTPUT>
          Optionally provide a filename for the output. To send to standard out (stdout), use "-"

  -b, --backend <BACKEND>
          Optionally select a backend for conversion
          
          [default: htmlbook]

          Possible values:
          - htmlbook: Produces "Htmlbook-like" HTML documents
          - json:     Displays the Abstract Syntax Tree generated by the parser

  -h, --help
          Print help (see a summary with '-h')
----

== Current State Notes (As of the Last README Commit)

We (more or less) now produce HTML output for the vast majority of "common"
asciidoc markup features. To borrow
https://github.com/nlopes/acdc/tree/main/acdc-parser[another exciting project's list]:

* [*] Document Headers (see limitations)
* [*] Section
* [*] Delimited Block
** [*] Comment
** [*] Example
** [*] Listing
** [ ] Literal (see limitations)
** [*] Open
** [*] Sidebar
** [*] Table
** [*] Pass
** [*] Quote
* [*] Paragraph (Note that I'm not currently taking into account indented, or literal source leafblocks)
** [*] Bold
** [*] Italic
** [*] Monospace
** [ ] Literal Monospace (see limitations)
** [*] Highlight (including the application of inline styles!)
** [*] Subscript / Superscript
* [*] Image (inline and block, with blocks optionally rendering as captioned figures)
* [*] Lists
** [*] Ordered
** [*] Unordered
** [ ] Checklists
* [*] Thematic Break
* [*] Page Break
* [*] Tables (see limitations)
* [*] Admonitions
* [*] Anchors
* [*] Attributes
* [*] Titles
* [*] Footnotes
* [*] Includes

* *Advanced* (Of the following, I am likely only interested in tagged regions, but maybe you then get offsets kind of for free).
** [ ] Offsets
** [ ] Tagged regions
* [ ] Conditionals
** [ ] ifdef
** [ ] ifndef
** [ ] ifeval

Check out `LIMITATIONS.adoc` for a more complete feature/limitations list.

== Project Goals 

A non-exhaustive list:

* Coverage of the majority, if not all, of the language features, probably
  initially targeting a set similar to that of the `libasciidoc` project.
* Clean, simple HTML output as a default
* Build-in styles on said html output, but, like, a very small set.
* Native "document" (`docx` or `odt`, probably `docx`) output; given that part
  of the goal of this project is to make it easier for non-technical writers to
  use asciidoc, and given that most publishers, journals, business people, etc.,
  still want MS Word files, these should be easy to produce. (Also
  differentiates this project's capabilities from that of `asciidoctor`)
* PyO3 hooks for use inside Python contexts... eventually

