use clap::{Parser, ValueEnum};
use std::path::PathBuf;

#[derive(Debug, ValueEnum, Clone)]
pub enum Backends {
    /// Produces "Htmlbook-like" HTML documents.
    Htmlbook,
    /// Displays the Abstract Syntax Tree generated by the parser
    Json,
}

/// Main entrypoint for asciidocr when called as executable
#[derive(Parser)]
#[command(name = "asciidocr")]
#[command(about="A Rust CLI and library for processing Asciidoc files.", long_about = None)]
pub struct Cli {
    /// Asciidoc file for processing. To read from standard input (stdin), use "-".
    pub file: String,

    /// Optionally provide a filename for the output.
    /// To send to standard out (stdout), use "-".
    #[arg(short = 'o', long = "out-file")]
    pub output: Option<String>,

    /// Optionally select a backend for conversion.
    #[arg(value_enum, short = 'b', long = "backend", default_value = "htmlbook")]
    pub backend: Backends,
}

pub fn read_output(args: Cli) -> Option<PathBuf> {
    match args.output {
        Some(ref output) => {
            if output == "-" {
                None
            } else {
                Some(PathBuf::from(output.clone()))
            }
        }
        None => {
            if args.file == "-" {
                // we put to stdout if stdin following asciidoctor
                None
            } else {
                let mut out_destination = PathBuf::new();
                out_destination.push(args.file.clone());
                match args.backend {
                    Backends::Htmlbook => out_destination.set_extension("html"),
                    Backends::Json => out_destination.set_extension("json"),
                };
                Some(out_destination)
            }
        }
    }
}
