use clap::{Parser, ValueEnum};

#[derive(Debug, ValueEnum, Clone)]
pub enum Backends {
    /// Produces "Htmlbook-like" HTML documents.
    Htmlbook,
    /// Displays the Abstract Syntax Tree generated by the parser
    Json,
}

/// Main entrypoint for asciidocr when called as executable
#[derive(Parser)]
#[command(name = "asciidocr")]
#[command(about="A Rust CLI and library for processing Asciidoc files.", long_about = None)]
pub struct Cli {
    /// Asciidoc file for processing. To read from standard input (stdin), use "-".
    pub file: String,

    /// Optionally provide a filename for the output.
    /// To send to standard out (stdout), use "-".
    #[arg(short = 'o', long = "out-file")]
    pub output: Option<String>,

    /// Optionally select a backend for conversion.
    #[arg(value_enum, short = 'b', long = "backend", default_value = "htmlbook")]
    pub backend: Backends,
}
